#!/bin/bash

set -e

exec 3>&1
exec 1>&2

# for jq
PATH=/usr/local/bin:$PATH

payload="$(cat <&0)"

token=$(jq -r '.source.token' <<< "$payload")
channel=$(jq -r '.params.channel' <<< "$payload")
text=$(jq -r '.params.text' <<< "$payload")

echo $channel
curl --location 'https://slack.com/api/chat.postMessage' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer '"$token"'' \
--data-raw '{
    "channel":"'"$channel"'",
    "text":"'"$text"' - '"$ATC_EXTERNAL_URL"'/builds/'"$BUILD_ID"'"
}'

#must emit version back to concourse
jq -n '{version:{ref:"0"}}' >&3