#!/bin/bash

set -e

exec 3>&1
exec 1>&2

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0
echo $payload
token=$(jq -r '.source.token' < "$payload")
channel=$(jq -r '.params.channel' < "$payload")
text=$(jq -r '.params.text' < "$payload")

curl --location 'https://slack.com/api/chat.postMessage' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer '"$token"'' \
--data-raw '{
    "channel":"'"$channel"'",
    "text":"'"$text"'"
}'

